# make zip file for deployment and deploy to GitHub Pages
name: Build and Deploy

on:
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false # Or true if you want to cancel running builds on new pushes

jobs:
  make-zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        if: hashFiles('requirements.txt') != ''
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create zip file
        run: python main.py # Creates build/my_files.zip

      # --- CHANGED STEP: Upload only the zip file ---
      - name: Upload zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: zip-file-artifact # Changed artifact name for clarity (optional)
          path: build/my_files.zip # Upload the specific file, not the directory

  build-deploy:
    runs-on: ubuntu-latest
    needs: make-zip
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # --- CHANGED STEP: Download the zip file artifact ---
      - name: Download zip artifact
        uses: actions/download-artifact@v4
        with:
          name: zip-file-artifact # Match the upload name
          # No path specified: downloads my_files.zip directly into the workspace root

      # --- GitHub Pages Steps ---
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Jekyll will now find my_files.zip in the root and copy it to _site/my_files.zip
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        # Uploads _site, which now contains my_files.zip at the root level

  # Deployment job (no changes needed here)
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

